export default function handler(req, res) {
  res.status(200).json({
    products: [
      {
        id: "d1",

        fileName: "Lorem ipsum dolor sit amet",
        directory: "src/pages",
        fileSize: "2M",
        company: "KHNP",
        site: "KR",
        unitNo: "3",
        equipment: "Condensor",
        createdAt: "2022-08-30T10:13:23.177Z",
        tubeSetting: "none",
        speed: "1.0 m/s",
        detector: "MS5800",
        probe: "Bobbin",
      },
      {
        id: "d2",
        fileName: "Aenean libero massa",
        directory: "src/redux",
        fileSize: "3M",
        company: "KHNP",
        site: "KR",
        unitNo: "2",
        equipment: "SG",
        createdAt: "2022-08-30T10:13:23.177Z",
        tubeSetting: "none",
        speed: "1.0 m/s",
        detector: "MS5800",
        probe: "Bobbin",
      },
      {
        id: "d3",
        fileName: "Aenean libero massa",
        directory: "src/redux",
        fileSize: "3M",
        company: "KHNP",
        site: "KR",
        unitNo: "2",
        equipment: "SG",
        createdAt: "2022-08-30T10:13:23.177Z",
        tubeSetting: "none",
        speed: "1.0 m/s",
        detector: "MS5800",
        probe: "Bobbin",
      },
      {
        id: "d4",
        fileName: "Aenean libero massa",
        directory: "src/redux",
        fileSize: "3M",
        company: "KHNP",
        site: "KR",
        unitNo: "2",
        equipment: "SG",
        createdAt: "2022-08-30T10:13:23.177Z",
        tubeSetting: "none",
        speed: "1.0 m/s",
        detector: "MS5800",
        probe: "Bobbin",
      },
      {
        id: "d5",
        fileName: "Aenean libero massa",
        directory: "src/redux",
        fileSize: "3M",
        company: "KHNP",
        site: "KR",
        unitNo: "2",
        equipment: "SG",
        createdAt: "2022-08-30T10:13:23.177Z",
        tubeSetting: "none",
        speed: "1.0 m/s",
        detector: "MS5800",
        probe: "Bobbin",
      },
    ],
  });
}
